In [1]:
def _is_in_danger(self, game_state, unit_id):
    #unit_position = game_state.get("unit_state")[unit_id].get("coordinates")
    gameboard = [
            ["-1", "0", "0", "0", "0", "0", "0"],
            ["0", "0", "1", "0", "0", "0", "0"],
            ["0", "0", "A", "0", "0", "0", "0"],
            ["0", "0", "0", "0", "0", "0", "0"],
            ["0", "0", "0", "0", "0", "0", "0"],
        ]
    unit_position = (2, 2)

    rows = len(gameboard)
    cols = len(gameboard[0])

    # Check for bombs in the same row
    for j in range(unit_position[1], max(0, unit_position[1] - 3) -1, -1):
        if int(gameboard[unit_position[0]][j]) == 1:
            return True
        elif int(gameboard[unit_position[0]][j]) == -1:
            break
    
    for j in range(unit_position[1], min(cols, unit_position[1] + 4)):
        if int(gameboard[unit_position[0]][j]) == 1:
            return True
        elif int(gameboard[unit_position[0]][j]) == -1:
            break
    
    # Check for bombs in the same column
    for i in range(unit_position[0], max(0, unit_position[0] - 3) -1, -1):
        if int(gameboard[i][unit_position[1]]) == 1:
            return True
        if int(gameboard[i][unit_position[1]]) == -1:
            break
        
    for i in range(unit_position[0], min(rows, unit_position[0] + 4)):
        if int(gameboard[i][unit_position[1]]) == 1:
            return True
        if int(gameboard[i][unit_position[1]]) == -1:
            break
    
    return False

In [9]:
import tensorflow as tf
import numpy as np

batch_size = 6
num_action = 5
actions = np.random.randint(low=0,high=num_action, size=batch_size)
probs = np.random.random((batch_size,num_action))

tf.gather(probs, actions, batch_dims=1)

<tf.Tensor: shape=(6,), dtype=float64, numpy=
array([0.79970213, 0.5407633 , 0.36541435, 0.61298706, 0.56857539,
       0.99109467])>

In [10]:
actions

array([4, 2, 2, 1, 1, 2])

In [11]:
probs

array([[0.94302171, 0.44758487, 0.74122136, 0.9532858 , 0.79970213],
       [0.84854428, 0.49089103, 0.5407633 , 0.46819486, 0.81083195],
       [0.84516789, 0.50295087, 0.36541435, 0.9249962 , 0.17804462],
       [0.71622306, 0.61298706, 0.50162636, 0.4663532 , 0.62251138],
       [0.14310726, 0.56857539, 0.66541009, 0.43763905, 0.82043003],
       [0.90962539, 0.34886789, 0.99109467, 0.72355344, 0.28909985]])